name: hneu_timetable
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  # flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  html: ^0.15.4
  intl: ^0.19.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
